version: "3.8"
services:
  
  server:
    build: 
      context: .
      target: development
    depends_on:
      - "mongo"
    environment:
      DEBUG: true
    ports:
      - "8000:8000"
    volumes:
    - "./src/app:/src/app"
    - "./src/development:/src/development"
    - "./src/tests:/src/tests"

  mongo:
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongod
      MONGO_INITDB_ROOT_PASSWORD: Password123!
      MONGO_INITDB_DATABASE: your_app
    volumes:
      - "mongo:/data/db"
      - "./src/development/init-db.js:/docker-entrypoint-initdb.d/init-db.js"
    expose:
      - "27017"
    restart: unless-stopped

volumes:
  mongo: